name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install setuptools
        run: |
          pip install setuptools==57.5.0
      - name: Setup nbdev-ci
        uses: fastai/workflows/quarto-ghp@master
        with:
         version: '3.10' # python version to use for this step    
  